// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqJ_2eld8EUgd1uHlpM6raVdM5N6ivPo',
    appId: '1:379874868707:web:bcc3efcfb3ad44f39db4d6',
    messagingSenderId: '379874868707',
    projectId: 'e-learning-d9f06',
    authDomain: 'e-learning-d9f06.firebaseapp.com',
    storageBucket: 'e-learning-d9f06.appspot.com',
    measurementId: 'G-R7EK4G74SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_W3A8XduVn_Ytl8cOPCmIfKYvxZVZgg',
    appId: '1:379874868707:android:006847d91a6e6c0c9db4d6',
    messagingSenderId: '379874868707',
    projectId: 'e-learning-d9f06',
    storageBucket: 'e-learning-d9f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvb6RieKDT5qYyGhLd9NrNfiUOft9eb8',
    appId: '1:379874868707:ios:98becd4858089ca79db4d6',
    messagingSenderId: '379874868707',
    projectId: 'e-learning-d9f06',
    storageBucket: 'e-learning-d9f06.appspot.com',
    androidClientId: '379874868707-rav2snih35v7bk86atedjc082qm3tdmv.apps.googleusercontent.com',
    iosClientId: '379874868707-51la5hafceg7mqjt8mfftvoevhe9m8d8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvb6RieKDT5qYyGhLd9NrNfiUOft9eb8',
    appId: '1:379874868707:ios:4a2ad3fe628a8d169db4d6',
    messagingSenderId: '379874868707',
    projectId: 'e-learning-d9f06',
    storageBucket: 'e-learning-d9f06.appspot.com',
    androidClientId: '379874868707-rav2snih35v7bk86atedjc082qm3tdmv.apps.googleusercontent.com',
    iosClientId: '379874868707-f0jd18o2nfcn6cu0b83i398uo0s3j85h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearning.RunnerTests',
  );
}
